### ISSUE TITLE
Comparison with Giraffe/Suave

### ISSUE THREAD

**Issue by delneg** [pimbrouwers/Falco#13]
Hi, this project looks great, but what i'd really love to see would be comparison with existing & popular web frameworks like Giraffe and Suave.
Also, it would be nice to include some benchmarks - one of core feature of .net platform is it's speed.

Thanks for your work & keep it up!

**Comment by pimbrouwers** [comment]
Hi Denis!

Thanks for reaching out.

Benchmarks are definitely on my radar. But at a high level, it should perform identically to the new Endpoint Routing feature in ASP.NET since Falco basically just provides a nice fsharp-y DSL to create endpoints. 

I'd be very curious to see how it holds up against Giraffe. Suave, likely wouldn't be a fair comparison since it is well known to not compete in terms of performance with Kestrel. However, if you use Dustin's ASP.NET core extension for Suave you could maybe include it in the test.

The reason I elected to go the route of building a DSL on top of the built-in routing was to gain any performance boosts the ASP team added. Who are all but guaranteed to not only be smarter than me, but also know the inner-workings of the stack more intimately.

I'm not entirely a benchmark expert. But here is the results of tests on my machine, which show that performance is quite comparable with a slight nod to Falco:

## Specs
![image](https://user-images.githubusercontent.com/4595453/79797914-23275e80-8326-11ea-9c51-552bfa6d6d9f.png)

## Hello world plain-text
Falco:
![image](https://user-images.githubusercontent.com/4595453/79797825-f5dab080-8325-11ea-97f5-1ba3e7f70747.png)

Giraffe:
![image](https://user-images.githubusercontent.com/4595453/79797860-0723bd00-8326-11ea-8b91-cc58f7065bcd.png)

## Hello someone plain-text (`hello/{name:string}`)

Falco:
![image](https://user-images.githubusercontent.com/4595453/79798267-bf516580-8326-11ea-8968-ad1ad9303988.png)

Giraffe:
![image](https://user-images.githubusercontent.com/4595453/79798416-f58ee500-8326-11ea-9a8b-fe6d006dcbfc.png)

**Comment by pimbrouwers** [comment]
Added to docs: https://github.com/pimbrouwers/Falco#benchmarks

**Comment by delneg** [comment]
That's great to have (and thanks for quick response btw), but could you add also feature comparsion / checklist / table ? (at least with Giraffe)
It would be nice for people trying to use Falco to know what they can and cannot do at the moment.

**Comment by pimbrouwers** [comment]
No problem at all!

I'll have to think about how best to frame that in terms of a comparison.  But I have some reservations with the "us or them" mentality it creates. Giraffe is amazing and so is Dustin. They deserve your support. 

Falco started of as an experiment, and evolved into a manifestation of my philosophies about low-friction web programming. 

The current documentation goes through all of Falco's features and probably only takes 10 minutes to read. So anyone familiar with Giraffe should see the similarities and differences rather quickly. 

At a high level the feature coverage is identical (routing, view engine, composable request handling etc.).

Falco also has support for:
- large file uploads (multipart streaming)
- built-in xss protection using the ASP antiforgery module. 

Some differences:
- Giraffe uses reflection to model bind. Whereas Falco assumes manual mapping and exposes utilities to make this much easier. 
- Giraffe has built in support for JSON. Falco expects you'll want to use your own preference of library (chrion, [Jay](https://GitHub.com/pimbrouwers/Jay) etc.).
- Giraffe offers composable routing. Falco takes a simpler, direct route -> handler approach. 

Perhaps we have the making of our table right there.

**Comment by panesofglass** [comment]
Also, endpoint routing vs custom routing. I was doing something similar with https://github.com/frank-fs/frank, though it stops at routing and builder config.

**Comment by pimbrouwers** [comment]
> Also, endpoint routing vs custom routing. I was doing something similar with https://github.com/frank-fs/frank, though it stops at routing and builder config.

I love the concepts in Frank. The idea of resources. Feels so natural for things like REST APIs.

**Comment by pimbrouwers** [comment]
@panesofglass @delneg here's a first stab. Thoughts?

|                    | Falco                                                                  | Giraffe                          |
|--------------------|------------------------------------------------------------------------|----------------------------------|
| Routing            | ASP.NET Endpoint routing                                               | Tail recursive F# implementation |
| Model Binding      | Manual, with utilities for reading values via `StringCollectionReader` | Custom reflection-based function |
| View Engine        | Native F#                                                              | Native F#                        |
| JSON               | "Bring your own"                                                       | Custom reflection-based function |
| XSS                | Built-in XSS protection support using Microsoft.AspNetCore.Antiforgery | N/A                              |
| Large-file uploads | Built-in multipart streaming                                           | N/A                              |

**Comment by delneg** [comment]
Yep that's what i kinda had in mind
I'm not into "use X instead of Y" but as a user of Giraffe it's easier to start using Falco if you know the differences
