### ISSUE TITLE
Sample Project Ideas

### ISSUE THREAD

**Issue by pimbrouwers** [pimbrouwers/Falco#23]
Opening the floor to ideas for sample projects. 

We currently have:
- Hello world
- Markdown blog

Some of my ideas:
- Todo MVC (kind of boring)
- A restaurant booking system (a la @ploeh)
- A public notepad (i.e. jsfiddle for plain-text)

**Comment by waghanza** [comment]
There is also https://github.com/gothinkster/realworld @pimbrouwers

**Comment by rishavs** [comment]
+1 for Realworld. Nothing better than a full webapp done in a framework to gauge its strengths and weaknesses.

Also, do consider outting the framework on Techempower. Techempower is fairly ubiquitous nowadays and it will be great to see how well Falco stacks up against other frameworks in pure performance, even if pure performance may not be the Falco goal. Having this data will be extremely helpful to people who are hesitant to try out F# as there is so low representation for fsharp tools and libraries in all these conversations.

https://www.techempower.com/benchmarks/

**Comment by pimbrouwers** [comment]
Thanks guys! Realworld seems like a great project. I'll see what I can do.

@rishavs We're actually already on techempower. I haven't done a PR for v2.0.0 yet though.

**Comment by bytesource** [comment]
This maybe is a bit off-topic, but whatever project you choose, I think it would be great if you could add a step-by-step tutorial  on how you built everything and your reasoning behind it.

I'm relatively new to F# and learning _only_ by desecting code often leads to frustrations, either because I don't understand a certain line of code and get stuck or because I want to know the "Why" behind an implementation. 

In fact, at this point, I'm more and more making decisions based on available real-world tutorials, as these allow me to make real progress ("actionable" as marketers like to say).

For example, I wanted to learn Bolero, but the tutorial on the website only gives a broad overview, which is not enough to use it in a project. On the other side, Zaid Ajaj wrote a book about Elmish, https://zaid-ajaj.github.io/the-elmish-book/#/, so I sticked with Elmish.

Just my two cents...

Stefan

**Comment by delneg** [comment]
You can also take a look at https://github.com/atsapura/CardManagement

**Comment by pimbrouwers** [comment]
Thanks @delneg I'll check that out. 

Development of the @gothinkster real-world app is taking place here: https://github.com/pimbrouwers/realworld-starter-kit

**Comment by brettrowberry** [comment]
Mostly, I want to see a good way to document APIs with OpenAPI/Swagger - whether manually, automatically, or somewhere in between.

**Comment by pimbrouwers** [comment]
@brettrowberry -- Sounds good. I imagine you're not alone, so how about over the holiday's I get a little more informed on the topic of OpenAPI v. Swagger and I'll do a little tutorial for the samples directory.

I'm also hopeful to finish the gothinkster impl. soon as well now that API and some higher patterns have solidified.

**Comment by brettrowberry** [comment]
Look at the index.html and swagger.JSON for a minimal working example. Basically, Swagger UI needs an OpenAPI document hosted on a known endpoint in either JSON or YML format.
https://github.com/brettrowberry/okapi/tree/main/WebRoot
