### ISSUE TITLE
html static webpages

### ISSUE THREAD

**Issue by May4m** [pimbrouwers/Falco#34]
Hi Pim. Thanks for putting time on Falco. I'm new to both F# and Falco and I'm learning through creating stuff 🙂  . One question I have is how do I render .html static files and edit the attributes and elements/nodes in Falco or something like template rendering.

**Comment by pimbrouwers** [comment]
Hi Sizwe,

Thanks for reaching out. 

I'm unsure what you're trying to do exactly. Are you trying to produce an HTML response? Or physically read an HTML file from disk, and render it's contents?

**Comment by May4m** [comment]
I'm trying to read html file from disk, modify and render the contents

**Comment by pimbrouwers** [comment]
Thank you for the clarification!

The Falco view engine won't help you with this, since it's based on pure F# functions. To me, it sounds like you need a template engine like [scriban](https://github.com/lunet-io/scriban), which will efficiently replace symbols found in string literals.

You can use the string you get from scriban, or another template engine with the `Response.ofHtmlString` in order to render the HTML with Falco.

``fsharp
let htmlStringHandler : HttpHandler =
    let html = "{html string from template engine}"
   
    html
    |> Response.ofHtmlString
```

For a complete example of how this works, checkout the [scriban example]https://github.com/pimbrouwers/Falco/tree/master/samples/ScribanExample) in the sample projects directory.

**Comment by May4m** [comment]
thanks, scriban sounds like exactly like what i need :)
