### ISSUE TITLE
Combine multiple class attributes

### ISSUE THREAD

**Issue by M-Mueller** [pimbrouwers/Falco#47]
Hi, would it be possible to combine multiple class attributes the way [Elm does it](https://package.elm-lang.org/packages/elm/html/latest/Html-Attributes#class)?

I'm using [tailwindcss](https://tailwindcss.com) and usually define some helper functions for commonly used components e.g.:
```
let button (attrs : list<XmlAttribute>) =
    Elem.button (
        Attr.class' "border rounded px-4 py-2 bg-blue-500 text-white"
        :: attrs
    )

let wideButton =
    button [ Attr.class' "w-64" ]
```
Unfortunately this doesn't work at the moment because only the first class attribute will be used by the browser. Do you think this would be a useful feature?

Also thank you for creating Falco!

**Comment by pimbrouwers** [comment]
Hi @M-Mueller thanks for reaching out and for the shout out! I appreciate you using (and hopefully enjoying) the framework.

This is a great question, and something I encountered as well early on when mucking about with the `Markup` module since I use tachyons (another atomic css lib). 

I think the function you're after though is `Attr.merge`:
https://github.com/pimbrouwers/Falco/blob/7a382287741ecc97b777af66d1ce0e5c824904d7/src/Falco/Markup.fs#L322

With this your code becomes: 

```fsharp
let button (attrs : XmlAttribute list) = 
    // safely combine custom attributes with defaults
    let defaultAttr = [ Attr.class' "border rounded px-4 py-2 bg-blue-500 text-white" ]
    let mergedAttr = attr |> Attr.merge defaultAttr
    Elem.button mergedAttr 

let wideButton = 
    button [ Attr.class' "w-64" ]
```

**Comment by M-Mueller** [comment]
Ah I missed that function. Does exactly what I wanted, thanks!
